spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: kis
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog.yml
    output-change-log: src/main/resources/changelog.xml